# TODO: Need to add packages here
#IMMUTABLEPACKAGES += quadui quadtelephony
GITSRC_immutable-quadui=git@github.com:fake/notconfigured.git
GITSRC_immutable-quadtelephony=git@github.com:fake/notconfigured.git

# This is what is used to run 'make publish'
PUBLISH=$(THEMEDIR)/publish.sh

.PHONY: publish
publish:
	@echo "Can't publish yet. Try again later"
	@exit 9
