IMMUTABLEPACKAGES += quad
GITSRC_immutable-quad=git@github.com:quadpbx/quad-package.git
#GITSRC_immutable-quadtelephony=git@github.com:fake/notconfigured.git

# Override core so it's git, not https:
GITSRC_immutable-core=git@github.com:phonebocx/pbxpackage-core.git

# This is what is used to run 'make publish'
PUBLISH=$(THEMEDIR)/publish.sh

.PHONY: publish
publish:
	@echo "Can't publish yet. Try again later"
	@exit 9
